#!/bin/sh
# -------------------------------------------------------------
# Authors:
# Gabriela Schirmer Mauricio <gabismauricio@gmail.com>
# -------------------------------------------------------------
# git-prerelease - automation for alpha, beta, pre-release tags
#

MSG_ONE=""
MSG_TWO=""

print_usage() {
  # TO DO
  echo "Usage: ..."
}

print_message () {
  echo ""
  echo "---------------------------------------------"
  echo "$MSG_ONE"
  echo "$MSG_TWO"
  echo "---------------------------------------------"
}

# get branch name
branch_full=`git branch --show-current`

# split name with / char
IFS='/'
read -rasplitIFS<<< "$branch_full"

# get branch prefix:
#   - feature
#   - support
#   - release
#   - hotfix
#   - main
#   - develop
prefix=${splitIFS[0]}

# get branch name
name=${splitIFS[1]}

if [ $prefix != "release" ] ; then
  MSG_ONE="This is not a release branch."
  MSG_TWO="Please, checkout to create a pre-release tag."
  print_message
  exit 0
fi

type=''
message=''

PARAMS=""

while (( "$#" )); do
  case "$1" in
    -t|--type)
      type=$2
      echo "$type"
      shift
      ;;
    -m|--message)
      message=$2
      echo "$message"
      shift
      ;;
    -*|--*=) # unsupported flags
      MSG_ONE="Error"
      MSG_TWO="This flag does not exist: $1" >&2
      print_message
      exit 1
      ;;
    *) # preserve positional arguments
      PARAMS="$PARAMS $1"
      shift
      ;;
  esac
done
